/*
 * This file is generated by jOOQ.
 */
package com.spyrosoft.jooq.db.tables.references


import com.spyrosoft.jooq.db.tables.AppUser



/**
 * The table <code>public.app_user</code>.
 */
val APP_USER: AppUser = AppUser.APP_USER
