/*
 * This file is generated by jOOQ.
 */
package com.spyrosoft.jooq.db.tables


import com.spyrosoft.jooq.db.Public
import com.spyrosoft.jooq.db.keys.APP_USER_PKEY
import com.spyrosoft.jooq.db.tables.records.AppUserRecord

import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AppUser(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AppUserRecord>?,
    aliased: Table<AppUserRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AppUserRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.app_user</code>
         */
        val APP_USER: AppUser = AppUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AppUserRecord> = AppUserRecord::class.java

    /**
     * The column <code>public.app_user.firstname</code>.
     */
    val FIRSTNAME: TableField<AppUserRecord, String?> = createField(DSL.name("firstname"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.app_user.lastname</code>.
     */
    val LASTNAME: TableField<AppUserRecord, String?> = createField(DSL.name("lastname"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.app_user.email</code>.
     */
    val EMAIL: TableField<AppUserRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.app_user.address</code>.
     */
    val ADDRESS: TableField<AppUserRecord, String?> = createField(DSL.name("address"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.app_user.id</code>.
     */
    val ID: TableField<AppUserRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    private constructor(alias: Name, aliased: Table<AppUserRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AppUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.app_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.app_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.app_user</code> table reference
     */
    constructor(): this(DSL.name("app_user"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AppUserRecord>): this(Internal.createPathAlias(child, key), child, key, APP_USER, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<AppUserRecord, Int?> = super.getIdentity() as Identity<AppUserRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<AppUserRecord> = APP_USER_PKEY
    override fun `as`(alias: String): AppUser = AppUser(DSL.name(alias), this)
    override fun `as`(alias: Name): AppUser = AppUser(alias, this)
    override fun `as`(alias: Table<*>): AppUser = AppUser(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AppUser = AppUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AppUser = AppUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AppUser = AppUser(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<String?, String?, String?, String?, Int?> = super.fieldsRow() as Row5<String?, String?, String?, String?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (String?, String?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (String?, String?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
