version: '3.2'
services:
  database:
    image: postgres:15
    container_name: kata-postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: kata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5432" ]
      interval: 5s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: pgadmin4_container
    build: ./
    image: dcagatay/pwless-pgadmin4
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: kata-postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: kata
    depends_on:
      - "database"
    ports:
      - "5050:80"
volumes:
  postgres:
